import type { Metadata, Viewport } from 'next';
import './globals.css';
import { Providers } from '@/components/providers';
import { PwaRegister } from '@/components/pwa-register';

export const metadata: Metadata = {
  title: 'Foster Care Home Management System',
  description:
    'A secure, private app for foster parents to manage placements, appointments, documents, medications, expenses, contacts, routines, and licensing.',
  robots: { index: false, follow: false },
  applicationName: 'Foster',
  manifest: '/manifest.webmanifest',
  // Standalone iOS web-app shell. The apple-touch-icon link is added automatically
  // from src/app/apple-icon.png (a real 180x180 PNG generated by scripts/gen-icons.cjs).
  appleWebApp: { capable: true, title: 'Foster', statusBarStyle: 'default' },
  icons: {
    icon: [
      { url: '/icon.svg', type: 'image/svg+xml' },
      { url: '/icon-192.png', sizes: '192x192', type: 'image/png' },
    ],
  },
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Coral brand bar in the installed app / mobile browser chrome.
  themeColor: '#dd6647',
  // Let content extend under the notch/home indicator; components use
  // env(safe-area-inset-*) so nothing is obscured.
  viewportFit: 'cover',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        <PwaRegister />
      </body>
    </html>
  );
}
